using Microsoft.EntityFrameworkCore.Migrations;

namespace Translator_app.Migrations
{
    public partial class PopulateWordsTableWithEnglishWords : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
              table: "Word",
              columns: new[] { "TextId", "Text", "LanguageId" },
              values: new object[,] {
                  { "1","Account Holder Name", "EN"},
                  { "2","Accounting and Finance", "EN"},
                  { "3","Active", "EN"},
                  { "4","Add New Fee", "EN"},
                  { "5","Add new Comment", "EN"},
                  { "6","Add new entry", "EN"},
                  { "7","Add New Vendor", "EN"},
                  { "8","Additional Editor Assignments / Management", "EN"},
                  { "9","Administration", "EN"},
                  { "10","Advertisement payment handling", "EN"},
                  { "11","Agency", "EN"},
                  { "12","Alipay Account", "EN"},
                  { "13","Analysis", "EN"},
                  { "14","Announcements", "EN"},
                  { "15","Annual closing tax return and audit", "EN"},
                  { "16","Annual Review Feedback", "EN"},
                  { "17","Apollo Manager Id - Data Quality", "EN"},
                  { "18","Apollo Manager Id - Resource", "EN"},
                  { "19","Applying payments in Caspian", "EN"},
                  { "20","AR follow up", "EN"},
                  { "21","Automated report", "EN"},
                  { "22","Bamboo", "EN"},
                  { "23","Bank Account Number", "EN"},
                  { "24","Bank Address", "EN"},
                  { "25","Bank Name", "EN"},
                  { "26","BI - Assist other department", "EN"},
                  { "27","BI - Assistance other offices", "EN"},
                  { "28","BI - Design Illustrations Graphic layout CSS", "EN"},
                  { "29","BI - Development solutions files", "EN"},
                  { "30","BI - Specific analysis (Tier Route Cost etc.)", "EN"},
                  { "31","Billing", "EN"},
                  { "32","BR support", "EN"},
                  { "33","Branch Name / Id", "EN"},
                  { "34","Bravo Roles", "EN"},
                  { "35","Bravo User", "EN"},
                  { "36","Budget preparation", "EN"},
                  { "37","Business management", "EN"},
                  { "38","Calling new Shoppers", "EN"},
                  { "39","Calls - Shoppers", "EN"},
                  { "40","Calls / meetings - Client SM", "EN"},
                  { "41","Calls / meetings - Internal", "EN"},
                  { "42","Calls Advertisement Providers", "EN"},
                  { "43","Calls Emails", "EN"},
                  { "44","Cancel", "EN"},
                  { "45","Cash Forecast", "EN"},
                  { "46","Caspian", "EN"},
                  { "47","Caspian (entering managing leads)", "EN"},
                  { "48","Caspian Office Users", "EN"},
                  { "49","Caspian Primary User", "EN"},
                  { "50","Caspian Roles", "EN"},
                  { "51","Change Requests", "EN"},
                  { "52","Choose one…", "EN"},
                  { "53","CL support", "EN"},
                  { "54","Client", "EN"},
                  { "55","Client Agreement Creation & Follow-up", "EN"},
                  { "56","Client communication", "EN"},
                  { "57","Client Excel reporting", "EN"},
                  { "58","Client related communication", "EN"},
                  { "59","Client Reporting", "EN"},
                  { "60","Client/Prospect – follow up", "EN"},
                  { "61","Client/Prospect  meeting", "EN"},
                  { "62","CN support", "EN"},
                  { "63","Cold Calls", "EN"},
                  { "64","Comment", "EN"},
                  { "65","Comment:", "EN"},
                  { "66","Comments", "EN"},
                  { "67","Company Name", "EN"},
                  { "68","Contract Expires", "EN"},
                  { "69","Contract Expiry Date", "EN"},
                  { "70","Copy", "EN"},
                  { "71","Cost-out RFP", "EN"},
                  { "72","Country Codes…", "EN"},
                  { "73","Create New Vendor", "EN"},
                  { "74","Created", "EN"},
                  { "75","Creating client proposal", "EN"},
                  { "76","Creating Process/Procedures", "EN"},
                  { "77","Credit memos entering/approving", "EN"},
                  { "78","Cross Departmental Support - BI", "EN"},
                  { "79","Cross Departmental Support - DQ", "EN"},
                  { "80","Cross Departmental Support - Finance", "EN"},
                  { "81","Cross Departmental Support - HR", "EN"},
                  { "82","Cross Departmental Support - IT", "EN"},
                  { "83","Cross Departmental Support - KAM", "EN"},
                  { "84","Cross Departmental Support - MKTG", "EN"},
                  { "85","Cross Departmental Support - RM", "EN"},
                  { "86","Cross Departmental Support - Sales", "EN"},
                  { "87","Currency", "EN"},
                  { "88","Data Checking in Excel", "EN"},
                  { "89","Data cleaning checking and matching", "EN"},
                  { "90","Date", "EN"},
                  { "91","Delete", "EN"},
                  { "92","Department", "EN"},
                  { "93","DQ Supervisor", "EN"},
                  { "94","Edit", "EN"},
                  { "95","Edit Timesheet Entry", "EN"},
                  { "96","Editing reports (First Line Editing)", "EN"},
                  { "97","Editor Assignments", "EN"},
                  { "98","Editor Invoicing", "EN"},
                  { "99","Email", "EN"},
                  { "100","E-mail", "EN"},
                  { "101","Employee Attendance Control", "EN"},
                  { "102","Employee Benefits payment", "EN"},
                  { "103","Employee Feedback", "EN"},
                  { "104","End", "EN"},
                  { "105","End date:", "EN"},
                  { "106","End time:", "EN"},
                  { "107","Entering Data in Accounting software", "EN"},
                  { "108","Entry overlaps with an existing entry:", "EN"},
                  { "109","EU support", "EN"},
                  { "110","Export", "EN"},
                  { "111","Fee", "EN"},
                  { "112","Fee Type", "EN"},
                  { "113","Fees", "EN"},
                  { "114","Fieldwork Partner", "EN"},
                  { "115","First Name", "EN"},
                  { "116","First Name", "EN"},
                  { "117","Follow up", "EN"},
                  { "118","Friday", "EN"},
                  { "119","Full Tier", "EN"},
                  { "120","Global Anti-Fraud Group Work", "EN"},
                  { "121","Global support", "EN"},
                  { "122","Health Care Assistance", "EN"},
                  { "123","Hide New Comment", "EN"},
                  { "124","Hiring / Interview", "EN"},
                  { "125","Hiring / Onboarding Process", "EN"},
                  { "126","Hold-A Management", "EN"},
                  { "127","Hold-B Management", "EN"},
                  { "128","Home", "EN"},
                  { "129","IBAN Code / Bank Account Number", "EN"},
                  { "130","Id", "EN"},
                  { "131","IN support", "EN"},
                  { "132","Independent User", "EN"},
                  { "133","Internal communication", "EN"},
                  { "134","Internal queries", "EN"},
                  { "135","Internal reporting", "EN"},
                  { "136","Interoffice communication", "EN"},
                  { "137","Invoicing", "EN"},
                  { "138","IO communication", "EN"},
                  { "139","Is Fieldwork Partner", "EN"},
                  { "140","IsAgency?", "EN"},
                  { "141","IT_Admin Tasks", "EN"},
                  { "142","KAM Supervisor", "EN"},
                  { "143","KPI Calculation", "EN"},
                  { "144","Last login", "EN"},
                  { "145","Last Name", "EN"},
                  { "146","Last Name", "EN"},
                  { "147","Lead Research", "EN"},
                  { "148","List timesheet entries", "EN"},
                  { "149","List View", "EN"},
                  { "150","Logout", "EN"},
                  { "151","Managing Contractors Vendors", "EN"},
                  { "152","Material creation", "EN"},
                  { "153","Modified", "EN"},
                  { "154","Monday", "EN"},
                  { "155","More", "EN"},
                  { "156","Name", "EN"},
                  { "157","Networking Events", "EN"},
                  { "158","New Hire - Training", "EN"},
                  { "159","New Timesheet Entry", "EN"},
                  { "160","Next", "EN"},
                  { "161","No", "EN"},
                  { "162","Office", "EN"},
                  { "163","Office Management", "EN"},
                  { "164","Official Jobtitle", "EN"},
                  { "165","OH and attributes calculation", "EN"},
                  { "166","Opt Fee is only applied if the starting status is Reviewed.", "EN"},
                  { "167","Opt. Fee", "EN"},
                  { "168","Organizing data Making template", "EN"},
                  { "169","Other Projects / Miscellaneous", "EN"},
                  { "170","P&L preparation", "EN"},
                  { "171","Partner communication", "EN"},
                  { "172","Payment Issues", "EN"},
                  { "173","Payment Method", "EN"},
                  { "174","People Development", "EN"},
                  { "175","People management", "EN"},
                  { "176","Performance tracking", "EN"},
                  { "177","PH Support", "EN"},
                  { "178","Phone Number", "EN"},
                  { "179","Phone number", "EN"},
                  { "180","Phone number isn't correct.", "EN"},
                  { "181","Pitching", "EN"},
                  { "182","Planning workload", "EN"},
                  { "183","Please select", "EN"},
                  { "184","Post advertisement", "EN"},
                  { "185","Preferred Language", "EN"},
                  { "186","Preparation for meetings", "EN"},
                  { "187","Prepare monthly Reports", "EN"},
                  { "188","Prepare Weekly Reports", "EN"},
                  { "189","Previous", "EN"},
                  { "190","Pricing Requests", "EN"},
                  { "191","Process control review", "EN"},
                  { "192","Process improvement", "EN"},
                  { "193","Profile", "EN"},
                  { "194","Project design", "EN"},
                  { "195","Project review with ops/PM", "EN"},
                  { "196","Project Setup / Prepare Guideline / Briefing", "EN"},
                  { "197","Providing training", "EN"},
                  { "198","PTO", "EN"},
                  { "199","Quality check (Second Line Editing)", "EN"},
                  { "200","Receiving training", "EN"},
                  { "201","Recruitment", "EN"},
                  { "202","Report automation", "EN"},
                  { "203","Reporting / Status Tracking /  Follow up", "EN"},
                  { "204","Reset Caspian Password", "EN"},
                  { "205","Revenue Confirmation", "EN"},
                  { "206","Review questionnaire / Shopper guideline", "EN"},
                  { "207","Rework - Analyst", "EN"},
                  { "208","Rework - Client", "EN"},
                  { "209","Rework - KAM", "EN"},
                  { "210","RM Supervisor", "EN"},
                  { "211","Roles", "EN"},
                  { "212","Rulez", "EN"},
                  { "213","Sales to Ops Transition", "EN"},
                  { "214","Saturday", "EN"},
                  { "215","Save", "EN"},
                  { "216","Save Comment", "EN"},
                  { "217","Save Fee", "EN"},
                  { "218","Scheduling", "EN"},
                  { "219","Search", "EN"},
                  { "220","Select", "EN"},
                  { "221","Select Agency", "EN"},
                  { "222","Select task", "EN"},
                  { "223","Self Assigned", "EN"},
                  { "224","SG support", "EN"},
                  { "225","Social Media", "EN"},
                  { "226","Spent hours", "EN"},
                  { "227","Start", "EN"},
                  { "228","Start - End", "EN"},
                  { "229","Start date:", "EN"},
                  { "230","Start time:", "EN"},
                  { "231","Sunday", "EN"},
                  { "232","Supervisor Name", "EN"},
                  { "233","Support", "EN"},
                  { "234","Surfmerchants", "EN"},
                  { "235","Survey", "EN"},
                  { "236","Switch to", "EN"},
                  { "237","Task", "EN"},
                  { "238","Task:", "EN"},
                  { "239","The right format is 'hh:mm'", "EN"},
                  { "240","This field can't be empty!", "EN"},
                  { "241","Thursday", "EN"},
                  { "242","Tier", "EN"},
                  { "243","Tier 1", "EN"},
                  { "244","Tier 2", "EN"},
                  { "245","Timesheet", "EN"},
                  { "246","Timesheetuser Username", "EN"},
                  { "247","Today", "EN"},
                  { "248","Tracker handling", "EN"},
                  { "249","Training - Self", "EN"},
                  { "250","Training - Self / coaching team member / external", "EN"},
                  { "251","Training / Briefing Shopper", "EN"},
                  { "252","Training / coaching team member / external", "EN"},
                  { "253","Translation", "EN"},
                  { "254","Translation of Guidelines other documents etc.", "EN"},
                  { "255","Tuesday", "EN"},
                  { "256","Type your comment here…", "EN"},
                  { "257","Type to search…", "EN"},
                  { "258","US support", "EN"},
                  { "259","Use the arrow keys on the keyboard (Up Down) to change the selection. Columns can be resized by the oblique lines in the header rows can be resized by the oblique lines in the first cell.", "EN"},
                  { "260","User Id", "EN"},
                  { "261","User Name", "EN"},
                  { "262","User Type", "EN"},
                  { "263","User With Agency", "EN"},
                  { "264","VAT/GST tax preparation and filing", "EN"},
                  { "265","Vendor", "EN"},
                  { "266","Vendor Fees", "EN"},
                  { "267","Vendor Id", "EN"},
                  { "268","Vendor Invoicing", "EN"},
                  { "269","Vendor Name", "EN"},
                  { "270","Vendor payments", "EN"},
                  { "271","Wave", "EN"},
                  { "272","Wednesday", "EN"},
                  { "273","Weekdays", "EN"},
                  { "274","Western Union Address", "EN"},
                  { "275","Whole Week", "EN"},
                  { "276","Yes", "EN"}

              });
        }


        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
