using Microsoft.EntityFrameworkCore.Migrations;

namespace Translator_app.Migrations
{
    public partial class PopulateWordsTableWithHungariansWords : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.InsertData(
              table: "Word",
              columns: new[] { "TextId", "Text", "LanguageId" },
              values: new object[,] {
              {"1","Számlatulajdonos neve", "HU"},
              {"2","Pénzügy", "HU"},
              {"3","Aktív", "HU"},
              {"4","Új díj létrehozása", "HU"},
              {"5","Új megjegyés létrehozása", "HU"},
              {"6","Új bejegyzés", "HU"},
              {"7","Új szolgáltató létrehozása", "HU"},
              {"8","Minőségellenőrzési megjegyzések", "HU"},
              {"9","Adminisztráció", "HU"},
              {"10","Hirdetési kifizetések kezelése", "HU"},
              {"11","Ügynökség", "HU"},
              {"12","Alipay fiók", "HU"},
              {"13","Analízis", "HU"},
              {"14","Közlemények", "HU"},
              {"15","Éves zárás, adóbevallás és ellenőrzés", "HU"},
              {"16","Teljesítményértékelés", "HU"},
              {"17","Apollo Manager Id - Data Quality", "HU"},
              {"18","Apollo Manager Id - Resource", "HU"},
              {"19","Bejövő fizetések könyvelése", "HU"},
              {"20","Kintlévőségkezelés", "HU"},
              {"21","Automatizált riport", "HU"},
              {"22","Bamboo", "HU"},
              {"23","Számlaszám", "HU"},
              {"24","Bank cím", "HU"},
              {"25","Bank név", "HU"},
              {"26","BI - más osztályok támogatása", "HU"},
              {"27","BI - más irodák támogatása", "HU"},
              {"28","BI - Design, Illustrations, Graphic layout, CSS", "HU"},
              {"29","BI - Development solutions files", "HU"},
              {"30","BI - Különleges elemzések (Tier, Route, Cost, etc.)", "HU"},
              {"31","Számlázás", "HU"},
              {"32","BR támogatás", "HU"},
              {"33","Fióknév / Id", "HU"},
              {"34","Bravo jogok", "HU"},
              {"35","Bravo felhasználó", "HU"},
              {"36","Költségvetés készítés", "HU"},
              {"37","Üzletmenet", "HU"},
              {"38","Új próbavásárkól hívása", "HU"},
              {"39","Hívás - Próbavásárló", "HU"},
              {"40","Hívás / megbeszélés - Ügyfél, SM", "HU"},
              {"41","Hívás / megbeszélés - belső", "HU"},
              {"42","Hirrdetési szolgáltatók hívása", "HU"},
              {"43","Calls Emails", "HU"},
              {"44","Visszavon", "HU"},
              {"45","Pénzügyi előrejelzés", "HU"},
              {"46","Caspian", "HU"},
              {"47","Caspian (Lead kezelés, léteehozás)", "HU"},
              {"48","Caspian Felhasználók", "HU"},
              {"49","Elsődleges Caspian felhasználó", "HU"},
              {"50","Caspian jogok", "HU"},
              {"51","Változási kérelem", "HU"},
              {"52","Válassz…", "HU"},
              {"53","CL támogatás", "HU"},
              {"54","Ügyfél", "HU"},
              {"55","Ügyfélszerződés létrehozása és nyomon követése", "HU"},
              {"56","Ügyfél kommunikáció", "HU"},
              {"57","Ügyfél Excel Riportálás", "HU"},
              {"58","Ügyfélel kapcsolatás kommunikáció", "HU"},
              {"59","Ügyfél Riportálás", "HU"},
              {"60","Ügyfél/Kapcsolat utánkövetés", "HU"},
              {"61","Ügyfél/Kapcsolat megbesy;l;s", "HU"},
              {"62","CN támogatás", "HU"},
              {"63","Cold Calls", "HU"},
              {"64","Megjegyzés", "HU"},
              {"65","Megjegyzés:", "HU"},
              {"66","Megjegyzések", "HU"},
              {"67","Cégnév", "HU"},
              {"68","Szerződés lejárat", "HU"},
              {"69","Szerződés lejárati ideje", "HU"},
              {"70","Másol", "HU"},
              {"71","Ajánlatkészítés", "HU"},
              {"72","Országkódok…", "HU"},
              {"73","Új szolgáltató létrehozása", "HU"},
              {"74","Létrehozva", "HU"},
              {"75","Ügyfélajánlat létrehozása", "HU"},
              {"76","Folyamat létrehozása", "HU"},
              {"77","Jóváíró számla létrehozás/kezelés", "HU"},
              {"78","Osztályközi támogatás - BI", "HU"},
              {"79","Osztályközi támogatás - DQ", "HU"},
              {"80","Osztályközi támogatás - Pénzügy", "HU"},
              {"81","Osztályközi támogatás - HR", "HU"},
              {"82","Osztályközi támogatás - IT", "HU"},
              {"83","Osztályközi támogatás - KAM", "HU"},
              {"84","Osztályközi támogatás - MKTG", "HU"},
              {"85","Osztályközi támogatás - RM", "HU"},
              {"86","Osztályközi támogatás - Sales", "HU"},
              {"87","Pénznem", "HU"},
              {"88","Adatellenőtzés Excelben", "HU"},
              {"89","Datatisztázás, ellenőrzés és összekötés", "HU"},
              {"90","Dátum", "HU"},
              {"91","Törlés", "HU"},
              {"92","Osztály", "HU"},
              {"93","DQ Csoportvezető", "HU"},
              {"94","Módosít", "HU"},
              {"95","Jelenléti ív módosítása", "HU"},
              {"96","Minőségellenőrzés (1. szintű)", "HU"},
              {"97","Editor megbízások", "HU"},
              {"98","Editor számlázás", "HU"},
              {"99","E-mail", "HU"},
              {"100","E-mail", "HU"},
              {"101","Munkavállalói részvétel ellenőrzése", "HU"},
              {"102","Munkavállalói juttatások kifizetése", "HU"},
              {"103","Munkavállalói visszajelzések", "HU"},
              {"104","Vége", "HU"},
              {"105","Vég dátum:", "HU"},
              {"106","Vég idő:", "HU"},
              {"107","Adatok bevitele a Számviteli rendszerbe", "HU"},
              {"108","A bejegyzés átfedésben van egy meglévő bejegyzéssel:", "HU"},
              {"109","EU támogatás", "HU"},
              {"110","Export", "HU"},
              {"111","Díj", "HU"},
              {"112","Díj típus", "HU"},
              {"113","Díjak", "HU"},
              {"114","Fieldwork Partner", "HU"},
              {"115","Keresztnév", "HU"},
              {"116","Keresztnév", "HU"},
              {"117","Utánkövetés", "HU"},
              {"118","Péntek", "HU"},
              {"119","Full Tier", "HU"},
              {"120","Csalásellenes Vizsgálat", "HU"},
              {"121","Global támogatás", "HU"},
              {"122","Egészségügyi segítségnyújtás", "HU"},
              {"123","Új megjegyzés elrejtése", "HU"},
              {"124","Felvétel / interjú", "HU"},
              {"125","Felvétel / Beléptetési folyamat", "HU"},
              {"126","Hold-A Kezelés", "HU"},
              {"127","Hold-B Kezelés", "HU"},
              {"128","Főoldal", "HU"},
              {"129","IBAN Kód / Számlaszám", "HU"},
              {"130","Azonosító", "HU"},
              {"131","IN támogatás", "HU"},
              {"132","Önáló felhasználó", "HU"},
              {"133","Belső kommunikáció", "HU"},
              {"134","Belső megkeresések", "HU"},
              {"135","Belső riportálás", "HU"},
              {"136","Irodákközti kommunikáció", "HU"},
              {"137","Számlázás", "HU"},
              {"138","Irodákközti kommunikáció", "HU"},
              {"139","Fieldwork Partner?", "HU"},
              {"140","Ügynökség?", "HU"},
              {"141","IT_admin feladatok", "HU"},
              {"142","KAM csoportvezető", "HU"},
              {"143","KPI számítás", "HU"},
              {"144","Utolsó belépés", "HU"},
              {"145","Vezetéknév", "HU"},
              {"146","Vezetéknév", "HU"},
              {"147","Lead keresés", "HU"},
              {"148","Jelenlétí ív tételeinek listázása", "HU"},
              {"149","Listanézet", "HU"},
              {"150","Kijelentkezés", "HU"},
              {"151","Szolgáltatók kezelése", "HU"},
              {"152","Szakmai anyagok létrehozása", "HU"},
              {"153","Módosítva", "HU"},
              {"154","Hétfő", "HU"},
              {"155","Több", "HU"},
              {"156","Név", "HU"},
              {"157","Kapcsolatépítési események", "HU"},
              {"158","Újbelépó tréning", "HU"},
              {"159","Új jelenléti ív tétel létrehozása", "HU"},
              {"160","Következő", "HU"},
              {"161","Nem", "HU"},
              {"162","Iroda", "HU"},
              {"163","Iroda kezelés", "HU"},
              {"164","Hivatalos Munkakör", "HU"},
              {"165","OH és attribótum számítás", "HU"},
              {"166","Az opciós díjat csak akkor alkalmazzák, ha a kiindulási státusz Reviewed.", "HU"},
              {"167","Opt. díj", "HU"},
              {"168","Adatok rendezése, sablon készítése", "HU"},
              {"169","Más projekt / Egyéb", "HU"},
              {"170","P&L készítés", "HU"},
              {"171","Partner kommunikáció", "HU"},
              {"172","Kifizetési kérdések ", "HU"},
              {"173","Fizatési mód", "HU"},
              {"174","munkavállaló fejlesztés", "HU"},
              {"175","Munkavállaló kezelése", "HU"},
              {"176","Teljesítménymérés", "HU"},
              {"177","PH támogatás", "HU"},
              {"178","Telefonszám", "HU"},
              {"179","Telefonszám", "HU"},
              {"180","A telefonszém nem megfelelő.", "HU"},
              {"181","Előadás (Pitch)", "HU"},
              {"182","Munkaszervezés", "HU"},
              {"183","Kérem válasszon", "HU"},
              {"184","Hirdetésfeladás", "HU"},
              {"185","Nyelvválasztás", "HU"},
              {"186","Megbeszélésre való felkészülés", "HU"},
              {"187","Havi riportok elkészítése", "HU"},
              {"188","Heti riportok elkészítése", "HU"},
              {"189","Előző", "HU"},
              {"190","Árazás", "HU"},
              {"191","Folyamatirányítás, felülvizsgálat", "HU"},
              {"192","Folyamatfejlesztés", "HU"},
              {"193","Profil", "HU"},
              {"194","Projekt dizájn", "HU"},
              {"195","Projekt felülvizsgálata ops/PM", "HU"},
              {"196","Projekt felállítása / Útmutató  / tájékoztató előkészítése", "HU"},
              {"197","Képzés tartása", "HU"},
              {"198","PTO", "HU"},
              {"199","Minőségellenőrzés (2. szintű)", "HU"},
              {"200","Tréningen való részvétel", "HU"},
              {"201","Toborzás", "HU"},
              {"202","Jelentés automatizálás", "HU"},
              {"203","Jelentés / állapotkövetés / nyomon követés", "HU"},
              {"204","Caspian Jelszó Visszaállítása", "HU"},
              {"205","Bevétel megerősítése", "HU"},
              {"206","Kérdőív ellenőrzés / Vásárlói útmutató", "HU"},
              {"207","Újrafeldolgozás - Elemző", "HU"},
              {"208","Újrafeldolgozás - Ügyfél", "HU"},
              {"209","Újrafeldolgozás - KAM", "HU"},
              {"210","RM Csoportvezető", "HU"},
              {"211","Jogok", "HU"},
              {"212","Rulez", "HU"},
              {"213","Sales to Ops Transition", "HU"},
              {"214","Szombat", "HU"},
              {"215","Mentés", "HU"},
              {"216","Megjegyzés mentése", "HU"},
              {"217","Díj mentése", "HU"},
              {"218","Ütemezés", "HU"},
              {"219","Keresés", "HU"},
              {"220","Válasz", "HU"},
              {"221","Ügynökség kiválasztása", "HU"},
              {"222","Feladat kiválasztása", "HU"},
              {"223","Self Assigned", "HU"},
              {"224","SG támogatás", "HU"},
              {"225","Social Media", "HU"},
              {"226","Óraszám", "HU"},
              {"227","Kezdés", "HU"},
              {"228","Kezdés - Vég", "HU"},
              {"229","Kedő dátum:", "HU"},
              {"230","Kezdő idő:", "HU"},
              {"231","Vasárnap", "HU"},
              {"232","Csoportvezető neve", "HU"},
              {"233","Támogatás", "HU"},
              {"234","Surfmerchants", "HU"},
              {"235","kérdőív", "HU"},
              {"236","Válts erre", "HU"},
              {"237","Feladat", "HU"},
              {"238","Feladat:", "HU"},
              {"239","A megfelelő formátum: \"óó: mm\"", "HU"},
              {"240","Ez a mező nem lehet üres!", "HU"},
              {"241","Csütörtök", "HU"},
              {"242","Tier", "HU"},
              {"243","Tier 1", "HU"},
              {"244","Tier 2", "HU"},
              {"245","Jelenléti ív", "HU"},
              {"246","Jelenléti ív felhasználó felhazsnálóneve", "HU"},
              {"247","Ma", "HU"},
              {"248","Tracker kezelés", "HU"},
              {"249","Tréning - saját", "HU"},
              {"250","Tréning - saját / csapat társ / külsős", "HU"},
              {"251","Tréning / Próbavásárló képzés", "HU"},
              {"252","Tréning - saját / csapat társ / külsős", "HU"},
              {"253","Fordítás", "HU"},
              {"254","Iránymutatások, egyéb dokumentumok fordítása", "HU"},
              {"255","Kedd", "HU"},
              {"256","Megjegyzés…", "HU"},
              {"257","Keresés megadás…", "HU"},
              {"258","US támogatás", "HU"},
              {"259","A kiválasztás módosításához használja a billentyűzet nyílgombjait (Fel, Le). Az oszlopok átméretezhetők a fejléc ferde vonalaival, a sorok pedig az első cellában lévő ferde vonalakkal.", "HU"},
              {"260","Felhasználó azonosító", "HU"},
              {"261","Felhasználónév", "HU"},
              {"262","Felhasználó típus", "HU"},
              {"263","Ügynökség felhasználója", "HU"},
              {"264","ÁFA / GST adó előkészítése és benyújtása", "HU"},
              {"265","Szolgáltató", "HU"},
              {"266","Szolgáltatói díjak", "HU"},
              {"267","Szolgáltatói azonosító", "HU"},
              {"268","Szolgáltatói számlázás", "HU"},
              {"269","Szolgáltatói neve", "HU"},
              {"270","Szolgáltatói kifizetések", "HU"},
              {"271","Wave", "HU"},
              {"272","Szerda", "HU"},
              {"273","Hétköznapok", "HU"},
              {"274","Western Union cím", "HU"},
              {"275","Teljes hét", "HU"},
              {"276","Igen", "HU"}
              });
        }


        protected override void Down(MigrationBuilder migrationBuilder)
        {

        }
    }
}
